<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>{{ title }}</title>
        <link rel="stylesheet" href="/components/reveal.js/css/reveal.css" type="text/css">
        <link rel="stylesheet" href="/components/reveal.js/css/theme/solarized.css" id="theme" type="text/css">
        <link rel="stylesheet" href="/css/base.css" type="text/css">
    </head>
    <body>
        {% block content %}{% endblock %}
    </body>
</html>
